### PR TITLE
Rewrite 1d plot acquisition plot

### PR DESCRIPTION
**Pull request by MechCoder**

### CODE REVIEW

**Comment by MechCoder** [comment]
@glouppe @amueller had suggested to use this plot which looks much better.

lcb

**Comment by amueller** [comment]
there should be no connection between the red dots in the legend ;)

**Comment by MechCoder** [comment]
lcb

**Comment by MechCoder** [comment]
Not sure why matplotlib does that by default

**Comment by glouppe** [comment]
Indeed, much better! To avoid clutter, could you show the legend only for epoch=1? Also maybe up to epoch=5 is enough.

**Comment by MechCoder** [comment]
Done!
gp_1

**Comment by glouppe** [comment]
Could you show the legend only for epoch=1? Then +1 for merge

**Comment by MechCoder** [comment]
done

**Comment by glouppe** [comment]
Thanks, merging :)

**Comment by betatim** [comment]
Nice plotting!

**Pull request merged**
