### PR TITLE
Add plot acquisition values example

### PR DESCRIPTION
**Pull request by MechCoder**

### CODE REVIEW

**Comment by MechCoder** [comment]
@glouppe 

figure_2-1

**Comment by glouppe** [comment]
Looks nice, but do we need 3d plots? 2d heatmap viridis-colored plots are easier to read, dont you find?

**Comment by MechCoder** [comment]
@glouppe Done! This is the new graph. The EI condition is behaving weirdly, don't you think.

figure_1-1

**Comment by MechCoder** [comment]
New graph with the colormap of the function as well.

figure_1-2

**Comment by glouppe** [comment]
Looks better! 

Yes, EI is weird. I would say there is a bug somewhere...

**Comment by MechCoder** [comment]
@glouppe I fixed the failing test. Can you merge this.

Also you may want to try out the plot_1d_demo example. As you move the slider, it plots the acquisition function values with the point being sampled in that iteration. You can supply any function that you want :-)

**Comment by glouppe** [comment]
@MechCoder I got weird blocky shapes when running plot_1d_demo :/

**Comment by MechCoder** [comment]
But as the slider is moved to the end, it replicates the parabola right?

If you observe, the weird shapes dip towards the minimum and rise towards the maximum of the function. (Or that is what I say to console myself)

**Pull request merged**
